###
POST http://localhost:2394/api/user
content-type: application/json

{
    "identifyId": "asdkjqwikjasdasd",
    "email": "kaka@kaka.com",
    "joinType": 1,
    "secureLevel": 0
}

###
GET http://localhost:2394/api/user/1
content-type: application/json

###
GET http://localhost:2394/api/user/allInfo/1
content-type: application/json

###
PATCH http://localhost:2394/api/user/1
content-type: application/json

{
    "secureLevel": 4
}

