###
POST http://localhost:2394/api/writingApplicate/applicate/1
content-type: application/json
id: 1
identify-id: asdkjqwikjasdasd

{
    "round": 1,
    "say": "asdwascasdasd1211111"
}

###
GET http://localhost:2394/api/writingApplicate/round/1
content-type: application/json

###
GET http://localhost:2394/api/writingApplicate/allInfo/round/1
content-type: application/json

